"""empty message

Revision ID: 741c95b57167
Revises: 
Create Date: 2025-12-01 16:58:28.834253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '741c95b57167'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('descricao'))

    op.drop_table('tarefa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('descricao'), ['descricao'], unique=True)

    op.drop_table('usuario')
    # ### end Alembic commands ###
